Flavor: !mux
    s2.small.1:
        name: s2.small.1
        cpu: 1
        memory: 1
        virt: kvm
    s2.medium.2:
        name: s2.medium.2
        cpu: 1
        memory: 2
        virt: kvm
    s2.large.2:
        name: s2.large.2
        cpu: 2
        memory: 4
        virt: kvm
    s2.xlarge.2:
        name: s2.xlarge.2
        cpu: 4
        memory: 8
        virt: kvm
    s2.2xlarge.2:
        name: s2.2xlarge.2
        cpu: 8
        memory: 16
        virt: kvm
    s2.4xlarge.2:
        name: s2.4xlarge.2
        cpu: 16
        memory: 32
        virt: kvm
    s2.8xlarge.2:
        name: s2.8xlarge.2
        cpu: 32
        memory: 64
        virt: kvm
    s2.medium.4:
        name: s2.medium.4
        cpu: 1
        memory: 4
        virt: kvm
    s2.large.4:
        name: s2.large.4
        cpu: 2
        memory: 8
        virt: kvm
    s2.xlarge.4:
        name: s2.xlarge.4
        cpu: 4
        memory: 16
        virt: kvm
    s2.2xlarge.4:
        name: s2.2xlarge.4
        cpu: 8
        memory: 32
        virt: kvm
    s2.4xlarge.4:
        name: s2.4xlarge.4
        cpu: 16
        memory: 64
        virt: kvm
    s2.8xlarge.4:
        name: s2.8xlarge.4
        cpu: 32
        memory: 128
        virt: kvm
    m2.large.8:
        name: m2.large.8
        cpu: 2
        memory: 16
        virt: kvm
    m2.xlarge.8:
        name: m2.xlarge.8
        cpu: 4
        memory: 32
        virt: kvm
    m2.2xlarge.8:
        name: m2.2xlarge.8
        cpu: 8
        memory: 64
        virt: kvm
    m2.4xlarge.8:
        name: m2.4xlarge.8
        cpu: 16
        memory: 128
        virt: kvm
    m2.8xlarge.8:
        name: m2.8xlarge.8
        cpu: 32
        memory: 256
        virt: kvm
    hc2.large.2:
        name: hc2.large.2
        cpu: 2
        memory: 4
        virt: kvm
    hc2.xlarge.2:
        name: hc2.xlarge.2
        cpu: 4
        memory: 8
        virt: kvm
    hc2.2xlarge.2:
        name: hc2.2xlarge.2
        cpu: 8
        memory: 16
        virt: kvm
    hc2.4xlarge.2:
        name: hc2.4xlarge.2
        cpu: 16
        memory: 32
        virt: kvm
    hc2.8xlarge.2:
        name: hc2.8xlarge.2
        cpu: 32
        memory: 64
        virt: kvm
    hc2.large.4:
        name: hc2.large.4
        cpu: 2
        memory: 8
        virt: kvm
    hc2.xlarge.4:
        name: hc2.xlarge.4
        cpu: 4
        memory: 16
        virt: kvm
    hc2.2xlarge.4:
        name: hc2.2xlarge.4
        cpu: 8
        memory: 32
        virt: kvm
    hc2.4xlarge.4:
        name: hc2.4xlarge.4
        cpu: 16
        memory: 64
        virt: kvm
    hc2.8xlarge.4:
        name: hc2.8xlarge.4
        cpu: 32
        memory: 128
        virt: kvm
    h2.3xlarge.10:
        name: h2.3xlarge.10
        cpu: 16
        memory: 128
        nic_count: 12
        disk_count: 1
        disk_size: 3200
        disk_type: nvme
        virt: kvm
    h2.3xlarge.20:
        name: h2.3xlarge.20
        cpu: 16
        memory: 256
        nic_count: 12
        disk_count: 1
        disk_size: 3200
        disk_type: nvme
        virt: kvm
    d2.xlarge.8:
        name: d2.xlarge.8
        cpu: 4
        memory: 32
        disk_count: 2
        disk_size: 1800
        disk_type: scsi
        virt: kvm
    d2.2xlarge.8:
        name: d2.2xlarge.8
        cpu: 8
        memory: 64
        disk_count: 4
        disk_size: 1800
        disk_type: scsi
        virt: kvm
    d2.4xlarge.8:
        name: d2.4xlarge.8
        cpu: 16
        memory: 128
        disk_count: 8
        disk_size: 1800
        disk_type: scsi
        virt: kvm
    d2.6xlarge.8:
        name: d2.6xlarge.8
        cpu: 24
        memory: 192
        disk_count: 12
        disk_size: 1800
        disk_type: scsi
        virt: kvm
    d2.8xlarge.8:
        name: d2.8xlarge.8
        cpu: 32
        memory: 256
        disk_count: 16
        disk_size: 1800
        disk_type: scsi
        virt: kvm
    d2.12xlarge.8:
        name: d2.12xlarge.8
        cpu: 48
        memory: 384
        disk_count: 24
        disk_size: 1800
        disk_type: scsi
        virt: kvm
    p1.2xlarge.8:
        name: p1.2xlarge.8
        cpu: 8
        memory: 64
        disk_count: 1
        disk_size: 800
        disk_type: nvme
        virt: kvm
    p1.4xlarge.8:
        name: p1.4xlarge.8
        cpu: 16
        memory: 128
        disk_count: 2
        disk_size: 800
        disk_type: nvme
        virt: kvm
    p1.8xlarge.8:
        name: p1.8xlarge.8
        cpu: 32
        memory: 256
        disk_count: 4
        disk_size: 800
        disk_type: nvme
        virt: kvm
